print("What is your name human?")
n = input()
print("How old are you?")
a = int(input())
print("How tall are you?")
h = float(input())
print ("How much is your weight?")
w = float(input())
bmi = w/(h**2)
print(f"{n}you are {a} years old and your BMI is {bmi}")