print("please enter the number of lives: ")
health= int(input())
print("please enter the level: ")
energy = int(input())
print("please enter shield level: ")
shield = int(input())
print("health has been set")
print("lives:",  "\u2665"*health)
print("energy:",  "\u2665"*energy)
print("shield:",  "\u2665"*shield)